//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCareApp.Data.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dayCareAppDbEntities : DbContext
    {
        public dayCareAppDbEntities()
            : base("name=dayCareAppDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Child> Childs { get; set; }
        public virtual DbSet<DayRegistration> DayRegistrations { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<InstitutionAdmin> InstitutionAdmins { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
    
        public virtual int SP_delete_Admin(Nullable<int> input_AdminId)
        {
            var input_AdminIdParameter = input_AdminId.HasValue ?
                new ObjectParameter("input_AdminId", input_AdminId) :
                new ObjectParameter("input_AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delete_Admin", input_AdminIdParameter);
        }
    
        public virtual int SP_delete_Child(Nullable<int> input_ChildId)
        {
            var input_ChildIdParameter = input_ChildId.HasValue ?
                new ObjectParameter("input_ChildId", input_ChildId) :
                new ObjectParameter("input_ChildId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delete_Child", input_ChildIdParameter);
        }
    
        public virtual int SP_delete_DayRegistration(Nullable<int> input_DayRegistrationId)
        {
            var input_DayRegistrationIdParameter = input_DayRegistrationId.HasValue ?
                new ObjectParameter("input_DayRegistrationId", input_DayRegistrationId) :
                new ObjectParameter("input_DayRegistrationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delete_DayRegistration", input_DayRegistrationIdParameter);
        }
    
        public virtual int SP_delete_Department(Nullable<int> input_DepartmentId)
        {
            var input_DepartmentIdParameter = input_DepartmentId.HasValue ?
                new ObjectParameter("input_DepartmentId", input_DepartmentId) :
                new ObjectParameter("input_DepartmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delete_Department", input_DepartmentIdParameter);
        }
    
        public virtual int SP_delete_Employee(Nullable<int> input_EmployeeId)
        {
            var input_EmployeeIdParameter = input_EmployeeId.HasValue ?
                new ObjectParameter("input_EmployeeId", input_EmployeeId) :
                new ObjectParameter("input_EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delete_Employee", input_EmployeeIdParameter);
        }
    
        public virtual int SP_delete_Institution(Nullable<int> input_InstitutionId)
        {
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delete_Institution", input_InstitutionIdParameter);
        }
    
        public virtual int SP_delete_InstitutionAdmin(Nullable<int> input_InstitutionAdminId)
        {
            var input_InstitutionAdminIdParameter = input_InstitutionAdminId.HasValue ?
                new ObjectParameter("input_InstitutionAdminId", input_InstitutionAdminId) :
                new ObjectParameter("input_InstitutionAdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delete_InstitutionAdmin", input_InstitutionAdminIdParameter);
        }
    
        public virtual int SP_delete_Parent(Nullable<int> input_ParentId)
        {
            var input_ParentIdParameter = input_ParentId.HasValue ?
                new ObjectParameter("input_ParentId", input_ParentId) :
                new ObjectParameter("input_ParentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delete_Parent", input_ParentIdParameter);
        }
    
        public virtual int SP_Insert_Admin(string input_FirstName, string input_LastName, string input_AppUserId, Nullable<int> input_PhoneNumber, string input_Email, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_FirstNameParameter = input_FirstName != null ?
                new ObjectParameter("input_FirstName", input_FirstName) :
                new ObjectParameter("input_FirstName", typeof(string));
    
            var input_LastNameParameter = input_LastName != null ?
                new ObjectParameter("input_LastName", input_LastName) :
                new ObjectParameter("input_LastName", typeof(string));
    
            var input_AppUserIdParameter = input_AppUserId != null ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(string));
    
            var input_PhoneNumberParameter = input_PhoneNumber.HasValue ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(int));
    
            var input_EmailParameter = input_Email != null ?
                new ObjectParameter("input_Email", input_Email) :
                new ObjectParameter("input_Email", typeof(string));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Admin", input_FirstNameParameter, input_LastNameParameter, input_AppUserIdParameter, input_PhoneNumberParameter, input_EmailParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Insert_Child(string input_FirstName, string input_LastName, Nullable<System.DateTime> input_Birthday, Nullable<int> input_DepartmentId, Nullable<int> input_InstitutionId, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_FirstNameParameter = input_FirstName != null ?
                new ObjectParameter("input_FirstName", input_FirstName) :
                new ObjectParameter("input_FirstName", typeof(string));
    
            var input_LastNameParameter = input_LastName != null ?
                new ObjectParameter("input_LastName", input_LastName) :
                new ObjectParameter("input_LastName", typeof(string));
    
            var input_BirthdayParameter = input_Birthday.HasValue ?
                new ObjectParameter("input_Birthday", input_Birthday) :
                new ObjectParameter("input_Birthday", typeof(System.DateTime));
    
            var input_DepartmentIdParameter = input_DepartmentId.HasValue ?
                new ObjectParameter("input_DepartmentId", input_DepartmentId) :
                new ObjectParameter("input_DepartmentId", typeof(int));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Child", input_FirstNameParameter, input_LastNameParameter, input_BirthdayParameter, input_DepartmentIdParameter, input_InstitutionIdParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Insert_DayRegistration(Nullable<System.DateTime> input_CheckInTime, Nullable<System.DateTime> input_CheckOutTime, Nullable<System.DateTime> input_ExpectedCheckOutTime, Nullable<int> input_ChildId, Nullable<int> input_InstitutionId, Nullable<int> input_ExpectedCheckOutParentId, Nullable<int> input_CheckInParentId, Nullable<int> input_CheckInEmployeeId, Nullable<int> input_CheckOutParentId, Nullable<int> input_CheckOutEmployeeId)
        {
            var input_CheckInTimeParameter = input_CheckInTime.HasValue ?
                new ObjectParameter("input_CheckInTime", input_CheckInTime) :
                new ObjectParameter("input_CheckInTime", typeof(System.DateTime));
    
            var input_CheckOutTimeParameter = input_CheckOutTime.HasValue ?
                new ObjectParameter("input_CheckOutTime", input_CheckOutTime) :
                new ObjectParameter("input_CheckOutTime", typeof(System.DateTime));
    
            var input_ExpectedCheckOutTimeParameter = input_ExpectedCheckOutTime.HasValue ?
                new ObjectParameter("input_ExpectedCheckOutTime", input_ExpectedCheckOutTime) :
                new ObjectParameter("input_ExpectedCheckOutTime", typeof(System.DateTime));
    
            var input_ChildIdParameter = input_ChildId.HasValue ?
                new ObjectParameter("input_ChildId", input_ChildId) :
                new ObjectParameter("input_ChildId", typeof(int));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_ExpectedCheckOutParentIdParameter = input_ExpectedCheckOutParentId.HasValue ?
                new ObjectParameter("input_ExpectedCheckOutParentId", input_ExpectedCheckOutParentId) :
                new ObjectParameter("input_ExpectedCheckOutParentId", typeof(int));
    
            var input_CheckInParentIdParameter = input_CheckInParentId.HasValue ?
                new ObjectParameter("input_CheckInParentId", input_CheckInParentId) :
                new ObjectParameter("input_CheckInParentId", typeof(int));
    
            var input_CheckInEmployeeIdParameter = input_CheckInEmployeeId.HasValue ?
                new ObjectParameter("input_CheckInEmployeeId", input_CheckInEmployeeId) :
                new ObjectParameter("input_CheckInEmployeeId", typeof(int));
    
            var input_CheckOutParentIdParameter = input_CheckOutParentId.HasValue ?
                new ObjectParameter("input_CheckOutParentId", input_CheckOutParentId) :
                new ObjectParameter("input_CheckOutParentId", typeof(int));
    
            var input_CheckOutEmployeeIdParameter = input_CheckOutEmployeeId.HasValue ?
                new ObjectParameter("input_CheckOutEmployeeId", input_CheckOutEmployeeId) :
                new ObjectParameter("input_CheckOutEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_DayRegistration", input_CheckInTimeParameter, input_CheckOutTimeParameter, input_ExpectedCheckOutTimeParameter, input_ChildIdParameter, input_InstitutionIdParameter, input_ExpectedCheckOutParentIdParameter, input_CheckInParentIdParameter, input_CheckInEmployeeIdParameter, input_CheckOutParentIdParameter, input_CheckOutEmployeeIdParameter);
        }
    
        public virtual int SP_Insert_Department(string input_DepartmentName, Nullable<int> input_PhoneNumber, Nullable<int> input_InstitutionId)
        {
            var input_DepartmentNameParameter = input_DepartmentName != null ?
                new ObjectParameter("input_DepartmentName", input_DepartmentName) :
                new ObjectParameter("input_DepartmentName", typeof(string));
    
            var input_PhoneNumberParameter = input_PhoneNumber.HasValue ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(int));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Department", input_DepartmentNameParameter, input_PhoneNumberParameter, input_InstitutionIdParameter);
        }
    
        public virtual int SP_Insert_Employee(string input_FirstName, string input_LastName, string input_AppUserId, Nullable<int> input_InstitutionId, Nullable<int> input_DepartmentId, Nullable<int> input_PhoneNumber, string input_Email, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_FirstNameParameter = input_FirstName != null ?
                new ObjectParameter("input_FirstName", input_FirstName) :
                new ObjectParameter("input_FirstName", typeof(string));
    
            var input_LastNameParameter = input_LastName != null ?
                new ObjectParameter("input_LastName", input_LastName) :
                new ObjectParameter("input_LastName", typeof(string));
    
            var input_AppUserIdParameter = input_AppUserId != null ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(string));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_DepartmentIdParameter = input_DepartmentId.HasValue ?
                new ObjectParameter("input_DepartmentId", input_DepartmentId) :
                new ObjectParameter("input_DepartmentId", typeof(int));
    
            var input_PhoneNumberParameter = input_PhoneNumber.HasValue ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(int));
    
            var input_EmailParameter = input_Email != null ?
                new ObjectParameter("input_Email", input_Email) :
                new ObjectParameter("input_Email", typeof(string));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Employee", input_FirstNameParameter, input_LastNameParameter, input_AppUserIdParameter, input_InstitutionIdParameter, input_DepartmentIdParameter, input_PhoneNumberParameter, input_EmailParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Insert_Institution(string input_InstitutionName, Nullable<int> input_PhoneNumber, string input_Email, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_InstitutionNameParameter = input_InstitutionName != null ?
                new ObjectParameter("input_InstitutionName", input_InstitutionName) :
                new ObjectParameter("input_InstitutionName", typeof(string));
    
            var input_PhoneNumberParameter = input_PhoneNumber.HasValue ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(int));
    
            var input_EmailParameter = input_Email != null ?
                new ObjectParameter("input_Email", input_Email) :
                new ObjectParameter("input_Email", typeof(string));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Institution", input_InstitutionNameParameter, input_PhoneNumberParameter, input_EmailParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Insert_InstitutionAdmin(string input_FirstName, string input_LastName, string input_AppUserId, Nullable<int> input_InstitutionId, Nullable<int> input_PhoneNumber, string input_Email, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_FirstNameParameter = input_FirstName != null ?
                new ObjectParameter("input_FirstName", input_FirstName) :
                new ObjectParameter("input_FirstName", typeof(string));
    
            var input_LastNameParameter = input_LastName != null ?
                new ObjectParameter("input_LastName", input_LastName) :
                new ObjectParameter("input_LastName", typeof(string));
    
            var input_AppUserIdParameter = input_AppUserId != null ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(string));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_PhoneNumberParameter = input_PhoneNumber.HasValue ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(int));
    
            var input_EmailParameter = input_Email != null ?
                new ObjectParameter("input_Email", input_Email) :
                new ObjectParameter("input_Email", typeof(string));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_InstitutionAdmin", input_FirstNameParameter, input_LastNameParameter, input_AppUserIdParameter, input_InstitutionIdParameter, input_PhoneNumberParameter, input_EmailParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Insert_Parent(string input_FirstName, string input_LastName, string input_Email, string input_PhoneNumber, Nullable<int> input_AppUserId, Nullable<int> input_InstitutionId, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_FirstNameParameter = input_FirstName != null ?
                new ObjectParameter("input_FirstName", input_FirstName) :
                new ObjectParameter("input_FirstName", typeof(string));
    
            var input_LastNameParameter = input_LastName != null ?
                new ObjectParameter("input_LastName", input_LastName) :
                new ObjectParameter("input_LastName", typeof(string));
    
            var input_EmailParameter = input_Email != null ?
                new ObjectParameter("input_Email", input_Email) :
                new ObjectParameter("input_Email", typeof(string));
    
            var input_PhoneNumberParameter = input_PhoneNumber != null ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(string));
    
            var input_AppUserIdParameter = input_AppUserId.HasValue ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(int));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Parent", input_FirstNameParameter, input_LastNameParameter, input_EmailParameter, input_PhoneNumberParameter, input_AppUserIdParameter, input_InstitutionIdParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Insert_ParentChild(Nullable<int> input_ChildId, Nullable<int> input_ParentId)
        {
            var input_ChildIdParameter = input_ChildId.HasValue ?
                new ObjectParameter("input_ChildId", input_ChildId) :
                new ObjectParameter("input_ChildId", typeof(int));
    
            var input_ParentIdParameter = input_ParentId.HasValue ?
                new ObjectParameter("input_ParentId", input_ParentId) :
                new ObjectParameter("input_ParentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_ParentChild", input_ChildIdParameter, input_ParentIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Address_Result> SP_Read_Address(Nullable<int> input_AddressId)
        {
            var input_AddressIdParameter = input_AddressId.HasValue ?
                new ObjectParameter("input_AddressId", input_AddressId) :
                new ObjectParameter("input_AddressId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Address_Result>("SP_Read_Address", input_AddressIdParameter);
        }
    
        public virtual int SP_Read_Admin(Nullable<int> input_AdminId)
        {
            var input_AdminIdParameter = input_AdminId.HasValue ?
                new ObjectParameter("input_AdminId", input_AdminId) :
                new ObjectParameter("input_AdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Read_Admin", input_AdminIdParameter);
        }
    
        public virtual int SP_Read_Admin_AppuserId(Nullable<int> input_AppUserId)
        {
            var input_AppUserIdParameter = input_AppUserId.HasValue ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Read_Admin_AppuserId", input_AppUserIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Child_Result> SP_Read_Child(Nullable<int> input_ChildId)
        {
            var input_ChildIdParameter = input_ChildId.HasValue ?
                new ObjectParameter("input_ChildId", input_ChildId) :
                new ObjectParameter("input_ChildId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Child_Result>("SP_Read_Child", input_ChildIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Child_InstitutionId_Result> SP_Read_Child_InstitutionId(Nullable<int> input_InstitutionId)
        {
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Child_InstitutionId_Result>("SP_Read_Child_InstitutionId", input_InstitutionIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Child_Parent_Result> SP_Read_Child_Parent(Nullable<int> input_ParentId)
        {
            var input_ParentIdParameter = input_ParentId.HasValue ?
                new ObjectParameter("input_ParentId", input_ParentId) :
                new ObjectParameter("input_ParentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Child_Parent_Result>("SP_Read_Child_Parent", input_ParentIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_DayRegistration_Result> SP_Read_DayRegistration(Nullable<int> input_DayRegistrationId)
        {
            var input_DayRegistrationIdParameter = input_DayRegistrationId.HasValue ?
                new ObjectParameter("input_DayRegistrationId", input_DayRegistrationId) :
                new ObjectParameter("input_DayRegistrationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_DayRegistration_Result>("SP_Read_DayRegistration", input_DayRegistrationIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Department_Result> SP_Read_Department(Nullable<int> input_DepartmentId)
        {
            var input_DepartmentIdParameter = input_DepartmentId.HasValue ?
                new ObjectParameter("input_DepartmentId", input_DepartmentId) :
                new ObjectParameter("input_DepartmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Department_Result>("SP_Read_Department", input_DepartmentIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Department_InstitutionId_Result> SP_Read_Department_InstitutionId(Nullable<int> input_InstitutionId)
        {
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Department_InstitutionId_Result>("SP_Read_Department_InstitutionId", input_InstitutionIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Employee_Result> SP_Read_Employee(Nullable<int> input_EmployeeId)
        {
            var input_EmployeeIdParameter = input_EmployeeId.HasValue ?
                new ObjectParameter("input_EmployeeId", input_EmployeeId) :
                new ObjectParameter("input_EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Employee_Result>("SP_Read_Employee", input_EmployeeIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Employee_AppUserId_Result> SP_Read_Employee_AppUserId(Nullable<int> input_AppUserId)
        {
            var input_AppUserIdParameter = input_AppUserId.HasValue ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Employee_AppUserId_Result>("SP_Read_Employee_AppUserId", input_AppUserIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Institution_Result> SP_Read_Institution(Nullable<int> input_InstitutionId)
        {
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Institution_Result>("SP_Read_Institution", input_InstitutionIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Institution_All_Result> SP_Read_Institution_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Institution_All_Result>("SP_Read_Institution_All");
        }
    
        public virtual ObjectResult<SP_Read_InstitutionAdmin_Result> SP_Read_InstitutionAdmin(Nullable<int> input_InstitutionAdminId)
        {
            var input_InstitutionAdminIdParameter = input_InstitutionAdminId.HasValue ?
                new ObjectParameter("input_InstitutionAdminId", input_InstitutionAdminId) :
                new ObjectParameter("input_InstitutionAdminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_InstitutionAdmin_Result>("SP_Read_InstitutionAdmin", input_InstitutionAdminIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_InstitutionAdmin_All_Result> SP_Read_InstitutionAdmin_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_InstitutionAdmin_All_Result>("SP_Read_InstitutionAdmin_All");
        }
    
        public virtual ObjectResult<SP_Read_InstitutionAdmin_AppUserId_Result> SP_Read_InstitutionAdmin_AppUserId(Nullable<int> input_AppUserId)
        {
            var input_AppUserIdParameter = input_AppUserId.HasValue ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_InstitutionAdmin_AppUserId_Result>("SP_Read_InstitutionAdmin_AppUserId", input_AppUserIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Parent_Result> SP_Read_Parent(Nullable<int> input_ParentId)
        {
            var input_ParentIdParameter = input_ParentId.HasValue ?
                new ObjectParameter("input_ParentId", input_ParentId) :
                new ObjectParameter("input_ParentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Parent_Result>("SP_Read_Parent", input_ParentIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Parent_AppUserId_Result> SP_Read_Parent_AppUserId(Nullable<int> input_AppUserId)
        {
            var input_AppUserIdParameter = input_AppUserId.HasValue ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Parent_AppUserId_Result>("SP_Read_Parent_AppUserId", input_AppUserIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Parent_ChildId_Result> SP_Read_Parent_ChildId(Nullable<int> input_ChildId)
        {
            var input_ChildIdParameter = input_ChildId.HasValue ?
                new ObjectParameter("input_ChildId", input_ChildId) :
                new ObjectParameter("input_ChildId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Parent_ChildId_Result>("SP_Read_Parent_ChildId", input_ChildIdParameter);
        }
    
        public virtual ObjectResult<SP_Read_Parent_InstitutionId_Result> SP_Read_Parent_InstitutionId(Nullable<int> input_InstitutionId)
        {
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Read_Parent_InstitutionId_Result>("SP_Read_Parent_InstitutionId", input_InstitutionIdParameter);
        }
    
        public virtual int SP_Update_Admin(Nullable<int> input_AdminId, string input_FirstName, string input_LastName, string input_AppUserId, Nullable<int> input_PhoneNumber, string input_Email, Nullable<int> input_AddressId, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_AdminIdParameter = input_AdminId.HasValue ?
                new ObjectParameter("input_AdminId", input_AdminId) :
                new ObjectParameter("input_AdminId", typeof(int));
    
            var input_FirstNameParameter = input_FirstName != null ?
                new ObjectParameter("input_FirstName", input_FirstName) :
                new ObjectParameter("input_FirstName", typeof(string));
    
            var input_LastNameParameter = input_LastName != null ?
                new ObjectParameter("input_LastName", input_LastName) :
                new ObjectParameter("input_LastName", typeof(string));
    
            var input_AppUserIdParameter = input_AppUserId != null ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(string));
    
            var input_PhoneNumberParameter = input_PhoneNumber.HasValue ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(int));
    
            var input_EmailParameter = input_Email != null ?
                new ObjectParameter("input_Email", input_Email) :
                new ObjectParameter("input_Email", typeof(string));
    
            var input_AddressIdParameter = input_AddressId.HasValue ?
                new ObjectParameter("input_AddressId", input_AddressId) :
                new ObjectParameter("input_AddressId", typeof(int));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Admin", input_AdminIdParameter, input_FirstNameParameter, input_LastNameParameter, input_AppUserIdParameter, input_PhoneNumberParameter, input_EmailParameter, input_AddressIdParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Update_Child(Nullable<int> input_ChildId, string input_FirstName, string input_LastName, Nullable<System.DateTime> input_Birthday, Nullable<int> input_DepartmentId, Nullable<int> input_InstitutionId, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_ChildIdParameter = input_ChildId.HasValue ?
                new ObjectParameter("input_ChildId", input_ChildId) :
                new ObjectParameter("input_ChildId", typeof(int));
    
            var input_FirstNameParameter = input_FirstName != null ?
                new ObjectParameter("input_FirstName", input_FirstName) :
                new ObjectParameter("input_FirstName", typeof(string));
    
            var input_LastNameParameter = input_LastName != null ?
                new ObjectParameter("input_LastName", input_LastName) :
                new ObjectParameter("input_LastName", typeof(string));
    
            var input_BirthdayParameter = input_Birthday.HasValue ?
                new ObjectParameter("input_Birthday", input_Birthday) :
                new ObjectParameter("input_Birthday", typeof(System.DateTime));
    
            var input_DepartmentIdParameter = input_DepartmentId.HasValue ?
                new ObjectParameter("input_DepartmentId", input_DepartmentId) :
                new ObjectParameter("input_DepartmentId", typeof(int));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Child", input_ChildIdParameter, input_FirstNameParameter, input_LastNameParameter, input_BirthdayParameter, input_DepartmentIdParameter, input_InstitutionIdParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Update_DayRegistration(Nullable<int> input_DayRegistrationId, Nullable<System.DateTime> input_CheckInTime, Nullable<System.DateTime> input_CheckOutTime, Nullable<System.DateTime> input_ExpectedCheckOutTime, Nullable<int> input_ChildId, Nullable<int> input_InstitutionId, Nullable<int> input_ExpectedCheckOutParentId, Nullable<int> input_CheckInParentId, Nullable<int> input_CheckInEmployeeId, Nullable<int> input_CheckOutParentId, Nullable<int> input_CheckOutEmployeeId)
        {
            var input_DayRegistrationIdParameter = input_DayRegistrationId.HasValue ?
                new ObjectParameter("input_DayRegistrationId", input_DayRegistrationId) :
                new ObjectParameter("input_DayRegistrationId", typeof(int));
    
            var input_CheckInTimeParameter = input_CheckInTime.HasValue ?
                new ObjectParameter("input_CheckInTime", input_CheckInTime) :
                new ObjectParameter("input_CheckInTime", typeof(System.DateTime));
    
            var input_CheckOutTimeParameter = input_CheckOutTime.HasValue ?
                new ObjectParameter("input_CheckOutTime", input_CheckOutTime) :
                new ObjectParameter("input_CheckOutTime", typeof(System.DateTime));
    
            var input_ExpectedCheckOutTimeParameter = input_ExpectedCheckOutTime.HasValue ?
                new ObjectParameter("input_ExpectedCheckOutTime", input_ExpectedCheckOutTime) :
                new ObjectParameter("input_ExpectedCheckOutTime", typeof(System.DateTime));
    
            var input_ChildIdParameter = input_ChildId.HasValue ?
                new ObjectParameter("input_ChildId", input_ChildId) :
                new ObjectParameter("input_ChildId", typeof(int));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_ExpectedCheckOutParentIdParameter = input_ExpectedCheckOutParentId.HasValue ?
                new ObjectParameter("input_ExpectedCheckOutParentId", input_ExpectedCheckOutParentId) :
                new ObjectParameter("input_ExpectedCheckOutParentId", typeof(int));
    
            var input_CheckInParentIdParameter = input_CheckInParentId.HasValue ?
                new ObjectParameter("input_CheckInParentId", input_CheckInParentId) :
                new ObjectParameter("input_CheckInParentId", typeof(int));
    
            var input_CheckInEmployeeIdParameter = input_CheckInEmployeeId.HasValue ?
                new ObjectParameter("input_CheckInEmployeeId", input_CheckInEmployeeId) :
                new ObjectParameter("input_CheckInEmployeeId", typeof(int));
    
            var input_CheckOutParentIdParameter = input_CheckOutParentId.HasValue ?
                new ObjectParameter("input_CheckOutParentId", input_CheckOutParentId) :
                new ObjectParameter("input_CheckOutParentId", typeof(int));
    
            var input_CheckOutEmployeeIdParameter = input_CheckOutEmployeeId.HasValue ?
                new ObjectParameter("input_CheckOutEmployeeId", input_CheckOutEmployeeId) :
                new ObjectParameter("input_CheckOutEmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_DayRegistration", input_DayRegistrationIdParameter, input_CheckInTimeParameter, input_CheckOutTimeParameter, input_ExpectedCheckOutTimeParameter, input_ChildIdParameter, input_InstitutionIdParameter, input_ExpectedCheckOutParentIdParameter, input_CheckInParentIdParameter, input_CheckInEmployeeIdParameter, input_CheckOutParentIdParameter, input_CheckOutEmployeeIdParameter);
        }
    
        public virtual int SP_Update_Department(Nullable<int> input_DepartmentId, string input_DepartmentName, Nullable<int> input_PhoneNumber, Nullable<int> input_InstitutionId)
        {
            var input_DepartmentIdParameter = input_DepartmentId.HasValue ?
                new ObjectParameter("input_DepartmentId", input_DepartmentId) :
                new ObjectParameter("input_DepartmentId", typeof(int));
    
            var input_DepartmentNameParameter = input_DepartmentName != null ?
                new ObjectParameter("input_DepartmentName", input_DepartmentName) :
                new ObjectParameter("input_DepartmentName", typeof(string));
    
            var input_PhoneNumberParameter = input_PhoneNumber.HasValue ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(int));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Department", input_DepartmentIdParameter, input_DepartmentNameParameter, input_PhoneNumberParameter, input_InstitutionIdParameter);
        }
    
        public virtual int SP_Update_Employee(Nullable<int> input_EmployeeId, string input_FirstName, string input_LastName, string input_AppUserId, Nullable<int> input_InstitutionId, Nullable<int> input_DepartmentId, Nullable<int> input_PhoneNumber, string input_Email, Nullable<int> input_AddressId, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_EmployeeIdParameter = input_EmployeeId.HasValue ?
                new ObjectParameter("input_EmployeeId", input_EmployeeId) :
                new ObjectParameter("input_EmployeeId", typeof(int));
    
            var input_FirstNameParameter = input_FirstName != null ?
                new ObjectParameter("input_FirstName", input_FirstName) :
                new ObjectParameter("input_FirstName", typeof(string));
    
            var input_LastNameParameter = input_LastName != null ?
                new ObjectParameter("input_LastName", input_LastName) :
                new ObjectParameter("input_LastName", typeof(string));
    
            var input_AppUserIdParameter = input_AppUserId != null ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(string));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_DepartmentIdParameter = input_DepartmentId.HasValue ?
                new ObjectParameter("input_DepartmentId", input_DepartmentId) :
                new ObjectParameter("input_DepartmentId", typeof(int));
    
            var input_PhoneNumberParameter = input_PhoneNumber.HasValue ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(int));
    
            var input_EmailParameter = input_Email != null ?
                new ObjectParameter("input_Email", input_Email) :
                new ObjectParameter("input_Email", typeof(string));
    
            var input_AddressIdParameter = input_AddressId.HasValue ?
                new ObjectParameter("input_AddressId", input_AddressId) :
                new ObjectParameter("input_AddressId", typeof(int));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Employee", input_EmployeeIdParameter, input_FirstNameParameter, input_LastNameParameter, input_AppUserIdParameter, input_InstitutionIdParameter, input_DepartmentIdParameter, input_PhoneNumberParameter, input_EmailParameter, input_AddressIdParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Update_Institution(Nullable<int> input_InstitutionId, string input_InstitutionName, Nullable<int> input_PhoneNumber, string input_Email, Nullable<int> input_AddressId, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_InstitutionNameParameter = input_InstitutionName != null ?
                new ObjectParameter("input_InstitutionName", input_InstitutionName) :
                new ObjectParameter("input_InstitutionName", typeof(string));
    
            var input_PhoneNumberParameter = input_PhoneNumber.HasValue ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(int));
    
            var input_EmailParameter = input_Email != null ?
                new ObjectParameter("input_Email", input_Email) :
                new ObjectParameter("input_Email", typeof(string));
    
            var input_AddressIdParameter = input_AddressId.HasValue ?
                new ObjectParameter("input_AddressId", input_AddressId) :
                new ObjectParameter("input_AddressId", typeof(int));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Institution", input_InstitutionIdParameter, input_InstitutionNameParameter, input_PhoneNumberParameter, input_EmailParameter, input_AddressIdParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Update_InstitutionAdmin(Nullable<int> input_InstitutionAdminId, string input_FirstName, string input_LastName, string input_AppUserId, Nullable<int> input_InstitutionId, Nullable<int> input_PhoneNumber, string input_Email, Nullable<int> input_AddressId, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_InstitutionAdminIdParameter = input_InstitutionAdminId.HasValue ?
                new ObjectParameter("input_InstitutionAdminId", input_InstitutionAdminId) :
                new ObjectParameter("input_InstitutionAdminId", typeof(int));
    
            var input_FirstNameParameter = input_FirstName != null ?
                new ObjectParameter("input_FirstName", input_FirstName) :
                new ObjectParameter("input_FirstName", typeof(string));
    
            var input_LastNameParameter = input_LastName != null ?
                new ObjectParameter("input_LastName", input_LastName) :
                new ObjectParameter("input_LastName", typeof(string));
    
            var input_AppUserIdParameter = input_AppUserId != null ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(string));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_PhoneNumberParameter = input_PhoneNumber.HasValue ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(int));
    
            var input_EmailParameter = input_Email != null ?
                new ObjectParameter("input_Email", input_Email) :
                new ObjectParameter("input_Email", typeof(string));
    
            var input_AddressIdParameter = input_AddressId.HasValue ?
                new ObjectParameter("input_AddressId", input_AddressId) :
                new ObjectParameter("input_AddressId", typeof(int));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_InstitutionAdmin", input_InstitutionAdminIdParameter, input_FirstNameParameter, input_LastNameParameter, input_AppUserIdParameter, input_InstitutionIdParameter, input_PhoneNumberParameter, input_EmailParameter, input_AddressIdParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    
        public virtual int SP_Update_Parent(Nullable<int> input_ParentId, string input_FirstName, string input_LastName, string input_Email, string input_PhoneNumber, Nullable<int> input_AppUserId, Nullable<int> input_InstitutionId, string input_StreetName, Nullable<int> input_PostCode, string input_City, string input_Country)
        {
            var input_ParentIdParameter = input_ParentId.HasValue ?
                new ObjectParameter("input_ParentId", input_ParentId) :
                new ObjectParameter("input_ParentId", typeof(int));
    
            var input_FirstNameParameter = input_FirstName != null ?
                new ObjectParameter("input_FirstName", input_FirstName) :
                new ObjectParameter("input_FirstName", typeof(string));
    
            var input_LastNameParameter = input_LastName != null ?
                new ObjectParameter("input_LastName", input_LastName) :
                new ObjectParameter("input_LastName", typeof(string));
    
            var input_EmailParameter = input_Email != null ?
                new ObjectParameter("input_Email", input_Email) :
                new ObjectParameter("input_Email", typeof(string));
    
            var input_PhoneNumberParameter = input_PhoneNumber != null ?
                new ObjectParameter("input_PhoneNumber", input_PhoneNumber) :
                new ObjectParameter("input_PhoneNumber", typeof(string));
    
            var input_AppUserIdParameter = input_AppUserId.HasValue ?
                new ObjectParameter("input_AppUserId", input_AppUserId) :
                new ObjectParameter("input_AppUserId", typeof(int));
    
            var input_InstitutionIdParameter = input_InstitutionId.HasValue ?
                new ObjectParameter("input_InstitutionId", input_InstitutionId) :
                new ObjectParameter("input_InstitutionId", typeof(int));
    
            var input_StreetNameParameter = input_StreetName != null ?
                new ObjectParameter("input_StreetName", input_StreetName) :
                new ObjectParameter("input_StreetName", typeof(string));
    
            var input_PostCodeParameter = input_PostCode.HasValue ?
                new ObjectParameter("input_PostCode", input_PostCode) :
                new ObjectParameter("input_PostCode", typeof(int));
    
            var input_CityParameter = input_City != null ?
                new ObjectParameter("input_City", input_City) :
                new ObjectParameter("input_City", typeof(string));
    
            var input_CountryParameter = input_Country != null ?
                new ObjectParameter("input_Country", input_Country) :
                new ObjectParameter("input_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Parent", input_ParentIdParameter, input_FirstNameParameter, input_LastNameParameter, input_EmailParameter, input_PhoneNumberParameter, input_AppUserIdParameter, input_InstitutionIdParameter, input_StreetNameParameter, input_PostCodeParameter, input_CityParameter, input_CountryParameter);
        }
    }
}
