//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCareApp.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public int addressId { get; set; }
        public string streetName { get; set; }
        public Nullable<int> postCode { get; set; }
        public string city { get; set; }
        public string country { get; set; }
    }
}
