//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCareApp.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayRegistrations
    {
        public int DayRegistrationId { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public Nullable<System.DateTime> ExpectedCheckOutTime { get; set; }
        public int FK_ChildId { get; set; }
        public int FK_InstitutionId { get; set; }
        public int FK_ExpectectedCheckOutParentId { get; set; }
        public int FK_CheckInParentId { get; set; }
        public int FK_CheckInEmployeeId { get; set; }
        public Nullable<int> FK_CheckOutParentId { get; set; }
        public Nullable<int> FK_CheckOutEmployeeId { get; set; }
    
        public virtual Childs Childs { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Parents Parents { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual Parents Parents1 { get; set; }
        public virtual Parents Parents2 { get; set; }
        public virtual Institutions Institutions { get; set; }
    }
}
