//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCareApp.Web.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dayCareAPPDBEntities1 : DbContext
    {
        public dayCareAPPDBEntities1()
            : base("name=dayCareAPPDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Adminstrator> Adminstrator { get; set; }
        public virtual DbSet<Child> Child { get; set; }
        public virtual DbSet<DayRegistration> DayRegistration { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Institution> Institution { get; set; }
        public virtual DbSet<Parent> Parent { get; set; }
        public virtual DbSet<ParentChild> ParentChild { get; set; }
        public virtual DbSet<IstitutionAdmin> IstitutionAdmin { get; set; }
    }
}
