//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCareApp.Web.Entities
{
    using DataContext;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class dayCareAPPDBEntities5 : DbContext
    {
        public dayCareAPPDBEntities5()
            : base("name=dayCareAPPDBEntities5")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Addresses> AddressSet { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<DayRegistration> DayRegistrations { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<InstitutionAdmin> InstitutionAdmins { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
      

   
    }
}
