//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCareApp.Web.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dayCareAPPDBEntities2 : DbContext
    {
        public dayCareAPPDBEntities2()
            : base("name=dayCareAPPDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Childs> Childs { get; set; }
        public virtual DbSet<DayRegistrations> DayRegistrations { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<InstitutionAdmins> InstitutionAdmins { get; set; }
        public virtual DbSet<Institutions> Institutions { get; set; }
        public virtual DbSet<Parents> Parents { get; set; }
    }
}
