//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayCareApp.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parents()
        {
            this.DayRegistrations = new HashSet<DayRegistrations>();
            this.DayRegistrations1 = new HashSet<DayRegistrations>();
            this.DayRegistrations2 = new HashSet<DayRegistrations>();
            this.Childs = new HashSet<Childs>();
        }
    
        public int ParentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string Email { get; set; }
        public string FK_ApplicationUserId { get; set; }
        public int FK_InstitutionId { get; set; }
        public int FK_AddressId { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayRegistrations> DayRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayRegistrations> DayRegistrations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayRegistrations> DayRegistrations2 { get; set; }
        public virtual Institutions Institutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Childs> Childs { get; set; }
    }
}
